"""initial schema

Revision ID: ccd26485d5cb
Revises: 
Create Date: 2026-09-29 06:15:57.060772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd26485d5cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regression_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('documents_run', sa.Integer(), nullable=False),
    sa.Column('per_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("split IN ('train','holdout','all')", name='regression_runs_split_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('split', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('owner_label', sa.String(), nullable=False),
    sa.Column('consent_note', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("document_type IN ('bank_statement','credit_card_bill','invoice')", name='documents_document_type_check'),
    sa.CheckConstraint("source = 'self' OR consent_note IS NOT NULL", name='documents_consent_check'),
    sa.CheckConstraint("source IN ('self','family_friend','concierge')", name='documents_source_check'),
    sa.CheckConstraint("split IN ('train','holdout')", name='documents_split_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='documents_id_tenant_id_key')
    )
    op.create_index('documents_tenant_sha256_idx', 'documents', ['tenant_id', 'sha256'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('parses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=False),
    sa.Column('layout_slug', sa.String(), nullable=True),
    sa.Column('layout_score', sa.Double(), nullable=True),
    sa.Column('runner_up_score', sa.Double(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('crossfoot_passed', sa.Boolean(), nullable=True),
    sa.Column('failed_checks', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('used_llm_fallback', sa.Boolean(), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('verified','document_inconsistent','parse_failed','unsupported','scanned','bad_password','error','needs_review')", name='parses_outcome_check'),
    sa.ForeignKeyConstraint(['document_id', 'tenant_id'], ['documents.id', 'documents.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('parses_document_created_idx', 'parses', ['document_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('base_parse_id', sa.UUID(), nullable=True),
    sa.Column('corrected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('crossfoot_passed', sa.Boolean(), nullable=False),
    sa.Column('is_gold', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_gold OR crossfoot_passed', name='corrections_gold_passed_check'),
    sa.ForeignKeyConstraint(['base_parse_id'], ['parses.id'], ),
    sa.ForeignKeyConstraint(['document_id', 'tenant_id'], ['documents.id', 'documents.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_gold_per_document', 'corrections', ['document_id'], unique=True, postgresql_where=sa.text('is_gold IS true'))
    op.create_table('layout_templates',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_parse_id', sa.UUID(), nullable=True),
    sa.Column('validated_successes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_parse_id'], ['parses.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO tenants (name) VALUES ('default') ON CONFLICT DO NOTHING"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('layout_templates')
    op.drop_index('one_gold_per_document', table_name='corrections', postgresql_where=sa.text('is_gold IS true'))
    op.drop_table('corrections')
    op.drop_index('parses_document_created_idx', table_name='parses')
    op.drop_table('parses')
    op.drop_index('documents_tenant_sha256_idx', table_name='documents', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('documents')
    op.drop_table('tenants')
    op.drop_table('regression_runs')
    # ### end Alembic commands ###
